### PR TITLE
Force default username & icon_url for Mattermost connector

### PR DESCRIPTION
**Pull request by vtrubesset**
It will respectively default to Kubemen and k8s logo

### CODE REVIEW

**Comment by trubesv** [comment]
@ramnes what do we want to do with this? :) I remember you were not very fond of overriding Mattermost defaults

**Comment by ramnes** [comment]
I don't mind overriding Mattermost values as an option, but I do mind doing this as a default. :)

**Comment by trubesv** [comment]
Agreed :)

**Comment by trubesv** [comment]
https://github.com/numberly/kubemen/pull/9

**Pull request closed without merging**
